baseURL = 'http://blog.adamelnaggar.com/'
languageCode = 'en-us'
title = "Adam El's Blog"
theme = "yinyang"

[author]
name = "Adam El-Naggar"
homepage = "https://adamelnaggar.com"

[params]
  description = "Occasional articles about my experience growing my small business and building online side projects."
headTitle = "Adam El's Blog"
mainSections = ["posts"]
extraHead = '<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Sigmar"><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inconsolata">'

[[params.socials]]
name = "About Me"
link = "https://adamelnaggar.com"
[[params.socials]]
name = "Twitter"
link = "https://twitter.com/adamelng/"
[[params.socials]]
name = "LinkedIn"
link = "https://www.linkedin.com/in/adamelnaggar/"
[[params.socials]]
name = "Instagram"
link = "https://www.instagram.com/adam.elng/"
[[params.socials]]
name = "GitHub"
link = "https://github.com/adamelnaggar"
