baseURL = 'http://blog.adamelnaggar.com/'
languageCode = 'en-us'
title = "Adam El's Blog"
theme = "yinyang"

[permalinks]
    categories =  "/:section/:slug"

[author]
name = "Adam El-Naggar"
homepage = "https://adamelnaggar.com"

[params]
mainSections = ["articles", "projects"]
homeSections = ["articles"]
headTitle = "Adam El's Blog"
description = "Occasional articles about my experience growing my small business and building online side projects."
extraHead = '<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Sigmar"><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inconsolata"><link rel="shortcut icon" type="image/png" href="/img/favicon.png"><link rel="shortcut icon" sizes="192x192" href="/img/favicon.png"><link rel="apple-touch-icon" href="/img/favicon.png">'

[[params.socials]]
name = "About"
link = "https://adamelnaggar.com"
[[params.socials]]
name = "Articles"
link = "/articles/"
[[params.socials]]
name = "Podcasts"
link = "/podcasts/"
[[params.socials]]
name = "Projects"
link = "/projects/"
[[params.socials]]
name = "Subscribe"
link = "/"
